name: OniaOpenCharmRun2ULenv
channels:
  - conda-forge
dependencies:
  - python = 3.9
  - xrootd
  - coffea == 0.7.20
  - pip
  - root == 6.26.2
  - jupyterlab >= 3
  - ipywidgets
  - pip:
    - pyyaml
    - uncertainties
    - tensorflow-macos==2.10
    - tensorflow-metal==0.6
    - tensorflow-probability==0.18
    - zfit