# Configuration file fo the fit functions.
# Fixed parameters have only one value, float parameters have three:
# par: [initial_value, min_value, max_value]
# path are arrays for every year pointing to the directory where the data is stored.

D0:
  mean: [1.864, 1.83, 1.89]
  p0: [78, -1000, 1000]
  p1: [-15, -1000, 1000]
  p2: [-9, -1000, 1000]
  sigma: [0.011, 1.0e-05, 0.999]
  signal_frac: [0.2, 0, 1]
Dstar:
  mean: [0.1455, 0.142, 0.158]
  lambda: [0.0005, 0.00001, 0.1]
  gamma: [-0.02, -0.1, 0.1]
  delta: [1.2, 0.01, 4]
  signal_frac: [0.3, 0, 1]
  A: [4, -20, 20]
  B: [0.57, -15, 10] 
  C: [-5, -20, 10]
  #Previous fit
  sigma1: [0.0001, 1.0e-06, 0.001]
  sigma2: [1.0e-05, 1.0e-06, 0.001]
  gauss1_frac: [0.3, 0, 1]
  gauss2_frac: [0.3, 0, 1]
  p0: [2.7e-3, 0.001, 5]
  p1: [-2.4e-1, -4, 4]
  p2: [5, 3, 10]
Upsilon:
  M1S: 9.46
  M2S: 10.02
  M3S: 10.35
  alpha_CB: [1.1, 0, 20]
  bkg_a1: [-0.19, -2, 2]
  bkg_a2: [-0.13, -2, 2]
  mscale: [1, 0, 1.2]
  n_CB: [8, 0, 30]
  sigma1S: [0.08, 0, 2]
  upsilon1S_frac: [0.2, 0, 1]
  upsilon2S_frac: [0.15, 0, 1]
  upsilon3S_frac: [0.1, 0, 1]
UpsilonDstar:
  dstar_mean: [0.1455, 0.142, 0.148]
  dstar_lambda: [0.0005, 0.000001, 4]
  dstar_gamma: [-0.02, -5, 5]
  dstar_delta: [1.2, 0.00005, 10]
  A: [-2, -45, 45]
  B: [0.57, -45, 45] 
  C: [-5, -45, 45]
  bkg_a1: [-0.06, -10, 10]
  bkg_a2: [-0.08, -10, 10]
  mscale: [1, 0.5, 1.3]
  sigma1S: [0.06, 0, 2.]
  upsilon1S_frac: [0.4, 0, 1]
  upsilon2S_frac: [0.15, 0, 1]
  signal_frac: [0.3, 0, 1]
  bkg1_frac: [0.3, 0, 1]
  bkg2_frac: [0.3, 0, 1]
  alpha_CB: [5.0, 1, 20]
  n_CB: [8, 0, 30]
  # Previous fit
  gauss1_frac: [0.3, 0, 1]
  dstar_sigma1: [0.0001, 1.0e-06, 0.001]
  dstar_sigma2: [1.0e-05, 1.0e-06, 0.001]
  p0: [2.7e-3, 0.001, 5]
  p1: [-2.4e-1, -4, 4]
  p2: [4, 3, 10]
path:
  '2016APV':
  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016B-ver2-HIPM
  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016C-HIPM
  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016D-HIPM
  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016E-HIPM
  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016F-HIPM
  '2016': 
  - output/RunII_trigger_processed_vtxfit/2016/MuOniaRun2016F
  - output/RunII_trigger_processed_vtxfit/2016/MuOniaRun2016G
  - output/RunII_trigger_processed_vtxfit/2016/MuOniaRun2016H
#  '2016':
#  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016B-ver2-HIPM
#  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016C-HIPM
#  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016D-HIPM
#  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016E-HIPM
#  - output/RunII_trigger_processed_vtxfit/2016APV/MuOniaRun2016F-HIPM
#  - output/RunII_trigger_processed_vtxfit/2016/MuOniaRun2016F
#  - output/RunII_trigger_processed_vtxfit/2016/MuOniaRun2016G
#  - output/RunII_trigger_processed_vtxfit/2016/MuOniaRun2016H
  '2017':
  - output/RunII_trigger_processed_vtxfit/2017/MuOniaRun2017B
  - output/RunII_trigger_processed_vtxfit/2017/MuOniaRun2017C
  - output/RunII_trigger_processed_vtxfit/2017/MuOniaRun2017D
  - output/RunII_trigger_processed_vtxfit/2017/MuOniaRun2017E
  - output/RunII_trigger_processed_vtxfit/2017/MuOniaRun2017F
  '2018':
  - output/RunII_trigger_processed_vtxfit/2018/MuOniaRun2018A
  - output/RunII_trigger_processed_vtxfit/2018/MuOniaRun2018B
  - output/RunII_trigger_processed_vtxfit/2018/MuOniaRun2018C
  - output/RunII_trigger_processed_vtxfit/2018/MuOniaRun2018D
